Using XCFit Pod from Cocoapods

diff --git a/XCFitDemo/Pods/OCSlimProject/Pod/Support/SharedSupport/LaunchFitnesse b/XCFitDemo/Pods/OCSlimProject/Pod/Support/SharedSupport/LaunchFitnesse
--- a/XCFitDemo/Pods/OCSlimProject/Pod/Support/SharedSupport/LaunchFitnesse
+++ b/XCFitDemo/Pods/OCSlimProject/Pod/Support/SharedSupport/LaunchFitnesse
@@ -1,7 +1,20 @@
-FITNESSE_PORT=8080
+##############
+# PROPERTIES #
+##############
+
+MY_PATH=$(dirname $0)
+SCRIPT_DIR=$(dirname "$(readlink "${BASH_SOURCE[0]}")")
 START=1
 CURL_CONNECTION_REFUSED_CODE=7
+
+#################
+# CONFIGURATION #
+#################
+
+FITNESSE_PORT=8080
+FITNESSE_EXECUTABLE_PATH=${SCRIPT_DIR}/fitnesse-standalone.jar
 FITNESSE_ROOT_CONTENT_FILE=FitnesseRoot/content.txt
+
 ####################################
 # Command Line Argument Processing #
 ####################################
@@ -12,7 +25,7 @@ while [ "$1" != "" ]; do
 		-p | --port )			shift
 								FITNESSE_PORT=$1
                                 ;;
-                                
+								
 		-k | --kill )			shift
 								START=0
                                 ;;
@@ -25,12 +38,27 @@ done
 # Subroutines #
 ###############
 
+function java_check {
+	if ! type java &> /dev/null ;  then
+		echo "Java (JRE) not found"
+    	echo "Download the latest version of Java?"
+		select yn in "Get Java for Mac" "Not Now"; do
+			case $yn in 
+				"Get Java for Mac" ) open "http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html"; break;;
+				"Not Now" ) break;;
+			esac
+		done
+		exit 0
+	fi
+}
+
 function fitnesse_kill {
 	lsof -n -i4TCP:$FITNESSE_PORT | awk ' { print $2 }' | sed -n 2p | xargs kill -9
 }
 
 function fitnesse_check {
-	if [ ! -f "fitnesse-standalone.jar" ]; then
+
+	if [ ! -f "${FITNESSE_EXECUTABLE_PATH}" ]; then
 		echo "Fitnesse-Standalone.jar missing!"
     	echo "Download the latest fitnesse-standlalone.jar to the current directory from Fitnesse.org"
 		select yn in "Goto http://fitnesse.org" "Not Now"; do
@@ -39,12 +67,18 @@ function fitnesse_check {
 				"Not Now" ) break;;
 			esac
 		done
+		popd 2>&1 > /dev/null
 		exit 0
 	fi
+
 }
 
 function fitnesse_start {
-	java -jar fitnesse-standalone.jar -e 0 -p ${FITNESSE_PORT} &
+	echo "# Fitnesse Info     "
+	echo "# Jar=${FITNESSE_EXECUTABLE_PATH}"
+	echo "# Port=${FITNESSE_PORT}"
+	echo "# Root=."
+	java -jar ${FITNESSE_EXECUTABLE_PATH} -e 0 -p ${FITNESSE_PORT} &
 }
 
 function fitnesse_wait {
@@ -63,7 +97,7 @@ function fitnesse_open {
 }
 
 function fitnesse_setup {
-	if [ ! -f "FitnesseRoot/content.txt" ]; then
+	if [ ! -f "${FITNESSE_ROOT_CONTENT_FILE}" ]; then
 		echo "''Auto Generated By !-"OCSlimProject"-! Do Not Modify This Page''" > $FITNESSE_ROOT_CONTENT_FILE
 		echo "!define TEST_SYSTEM {slim}" >> $FITNESSE_ROOT_CONTENT_FILE
 		echo "!define TEST_RUNNER {!-./OCSlimProjectTestRunner.sh-!}" >> $FITNESSE_ROOT_CONTENT_FILE
@@ -83,6 +117,10 @@ function fitnesse_launch {
 
 function fitnesse_main {
 
+	pushd $MY_PATH 2>&1 > /dev/null
+	
+	# Check Java Exists	
+	java_check
 	# Check Fitnesse Exists
 	fitnesse_check	
 	# Enable Job Control
@@ -91,6 +129,9 @@ function fitnesse_main {
 	fitnesse_launch
 	# Return Foreground control to Fitnesse
 	fg %1
+	
+	popd 2>&1 > /dev/null
+	
 }
 
 
@@ -105,7 +146,7 @@ function main {
 	0)  echo "Killing Processes on Port $FITNESSE_PORT"
 		fitnesse_kill
 		;;
-	1)  echo  "Starting Fitnesse on Port $FITNESSE_PORT"
+	1)  echo  "Launching Fitnesse"
 		fitnesse_main
 		;;
 	esac
